module.exports = require('./lib/StreamHelper')
module.exports.StreamHelper = require('./lib/StreamHelper')
module.exports.StreamReader = require('./lib/StreamReader')
module.exports.EndOfStreamError = require('./lib/EndOfStreamError')
module.exports.StreamMonitor = require('./lib/StreamMonitor')