name: Build
on:
  push:

jobs:
  check_eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        sudo npm install -g eslint
    - run: eslint index.js --ext .js,.jsx,.ts,.tsx
  npm:
    name: npm-publish
    if: "github.event_name == 'push'"
    runs-on: ubuntu-latest
    needs: [check_eslint]
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 16
        registry-url: 'https://registry.npmjs.org'
    - name: Install modules
      run: |
        npm install
    - run: |
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')
        jq '.version="'"$VERSION"'"' package.json > /tmp/a
        mv /tmp/a package.json
      if: "startsWith(github.ref, 'refs/tags/v')"
    - run: |
        npm whoami
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - run: |
        npm publish
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      if: "startsWith(github.ref, 'refs/tags/v')"
    - uses: actions/setup-node@v2
      with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      if: "startsWith(github.ref, 'refs/tags/v')"
    - run: |
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      if: "startsWith(github.ref, 'refs/tags/v')"